twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    
    globals:
        mycustom_variable: 12345
        sitename: '%env(SITENAME)%'

when@test:
    twig:
        strict_variables: true
